version: 1.2.4

cache: true

registration:
  socialLogins:
    - "discord"
    - "facebook"
    - "github"
    - "google"
    - "openid"

endpoints:
  custom:
    - name: nest-rag
      type: openai
      baseURL: http://mi-nest-api-dev.railway.internal:3000/v1
      apiKey: dev-key
      models:
        default: [rag-nest]
      headers:
        x-api-key: ${API_KEY}